# Generated by Django 4.2.7 on 2024-12-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={},
        ),
    ]
