# Generated by Django 4.2.7 on 2024-12-21 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificado_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='data_emissao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='nome_participante',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('PENDENTE', 'Pendente'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together={('evento', 'usuario')},
        ),
    ]
